name: Collect Crypto CSV

on:
  schedule:
    - cron: '0 * * * *'  # toutes les heures
  workflow_dispatch:      # permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: pip install pandas requests
    - name: Run collector
      run: python collect_crypto.py
    - name: Commit CSV
      run: |
       git config --global user.name "GitHub Actions"
       git config --global user.email "actions@github.com"
       git checkout -b data-update || git checkout data-update
       git add crypto_data.csv
       git commit -m "Update crypto CSV [skip ci]" || echo "No changes"
       git push -u origin data-update --force
